name: Publishing to NPM
on:
  push:
    branches:
      - master
    paths:
      - "package.json"
  workflow_call:
    inputs:
      if_bump:
        type: boolean
    secrets:
      NPM_TOKEN:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@sushiswap'
          cache: 'yarn'
      - run: yarn
      - run: yarn test
      - run: yarn build
      - if: inputs.if_bump == true
        name: bump & publish
        run: |
          git config --global user.email "form@sushi.com"
          git config --global user.name "tokenlistform[bot]"
          yarn publish --new-version minor
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: inputs.if_bump == ''
        name: publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}